MyDevelopmentOrg/src/objects/Permission_Set__c.object
<CustomObject>
    <description>This is a child of permission set groupings and is used to assign permission sets automatically to users.</description>
    <fields>
        <fullName>Permission_Set_Developer_Name__c</fullName>
        <description>This is the developer name of the permission set to assign to the user.</description>
        <inlineHelpText>This is the developer name of the permission set to assign to the user.</inlineHelpText>
        <label>Permission Set Developer Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_Set_Grouping__c</fullName>
        <description>This is the grouping that the permission set applies to.</description>
        <label>Permission Set Grouping</label>
        <referenceTo>Permission_Set_Grouping__c</referenceTo>
        <relationshipLabel>Permission Sets</relationshipLabel>
        <relationshipName>Permission_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Permission Set</label>
    <nameField>
        <displayFormat>PSGC-{000000}</displayFormat>
        <label>Permission Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MyDevelopmentOrg/src/objects/Permission_Set_Grouping__c.object
<CustomObject>
    <description>This is the object for grouping permission sets by feature and functionality area for filtering on permission sets.</description>
    <label>Permission Set Grouping</label>
    <nameField>
        <label>PSG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Set Groupings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDevelopmentOrg/src/classes/permissionSetGroupingFlow.cls
/****************************************************************
 * @Creator: Jeremiah Dohn
 * @Created Date: 2016-07-31
 * @Last Modifier: Jeremiah Dohn
 * @Last Modified Date: 2016-07-31
 * 
 * @Description: This is a flow plugin for accessing the random number generator in apex.
 * 
 * @Inputs: Permission Set Grouping Name - this is the grouping of permission sets to retrieve
 * 
 * @Outputs: Result - this is the result of the retrieval
 * 
 * **************************************************************/
global class permissionSetGroupingFlow implements Process.Plugin{
    
    global Process.PluginResult invoke(Process.PluginRequest request){
        
        Map<String,String> result = new Map<String,String>();
        
        String psgn = (String) request.inputParameters.get('Permission Set Grouping Name');
        
        Set<String> psSet = new Set<String>();
        String resultValue = '';
        
        // Get a list of the permission set developer names and then retrieve the permission sets
        for(Permission_Set__c ps : [SELECT Permission_Set_Developer_Name__c FROM Permission_Set__c
                                    WHERE Permission_Set_Grouping__r.Name = :psgn]){
            psSet.add(ps.Permission_Set_Developer_Name__c);                             
       	}
        
        List<PermissionSet> psList = new List<PermissionSet>([SELECT Id FROM PermissionSet
                                                              WHERE Name IN :psSet]);
        for(integer i = 0; i < psList.size(); i++){
            if(i < psList.size() - 1){
                resultValue += psList[i].Id + ',';  
            } else {
                resultValue += psList[i].Id;  
            }               
        }
		
        if(resultValue != ''){
            result.put('Result', resultValue);
        }
        
        return new Process.PluginResult(result); 
       
    }
    
    global process.PluginDescribeResult describe() {
        Process.PluginDescribeResult result = new Process.PluginDescribeResult(); 
        result.Name = 'Permission Set Grouping';
        result.Tag = 'Permission Set Grouping';
        
        // Set description
        result.Description ='This plugin will retrieve the permission set grouping child items and return the IDs for usage in flow.';

        // Set input parameters
        result.inputParameters = new List<Process.PluginDescribeResult.InputParameter>();
        result.inputParameters.add(new Process.PluginDescribeResult.inputParameter('Permission Set Grouping Name', Process.PluginDescribeResult.ParameterType.String, true));
        
        result.outputParameters = new List<Process.PluginDescribeResult.OutputParameter>(); 
        result.outputParameters.add(new Process.PluginDescribeResult.outputParameter('Result', Process.PluginDescribeResult.ParameterType.String));

        return result;
        
    }
    

}